### ISSUE TITLE
No response from server

### ISSUE THREAD

**Issue by flyfishMT** [sanketbajoria/ssh2-promise#78]
I consistently get the error 

> Error: No response from server
>     at Socket.<anonymous> (/app/node_modules/ssh2-promise/node_modules/ssh2/lib/client.js:764:19)
>     at Socket.emit (events.js:315:20)
>     at TCP.<anonymous> (net.js:673:12)

The first few times I call a function that uses your library.  Eventually it works.  I know that [this is an error from ssh2](https://github.com/mscdex/ssh2/blob/master/lib/client.js#L764), but thought that it might be cause be the usage of ssh2 in ssh2-promise, or how I'm using ssh2-promise?  

Psuedo-code:

```
const ssh = new SSH2Promise({
  host: <hostname>,
  username: <username>,
  identity: <path to private key>,
});


module.exports = async (searchText) => {
  const MAX = 100;
  const fileToSearch = <path to file>;
  // todo - sanitize uid
  const cmd = `/bin/grep -wi ${searchText} ${fileToSearch} | tail -n ${MAX} | sort -r`;
  const stdout = await ssh.exec(cmd);
  const results = stdout && stdout.split('\n').filter((i) => i !== '');
  return results;
};
```
I appreciate any help pointing me in the right direction.

**Comment by sanketbajoria** [comment]
@flyfishMT can you please enable debug log, by passing debug function to SSH configuration. Most probably ssh server is getting disconnected.

**Comment by flyfishMT** [comment]
@sanketbajoria thanks I will work on this and report back. It's a little difficult as we are only encountering this error in production

**Comment by flyfishMT** [comment]
@sanketbajoria I was able to reproduce but don't want to post everything up, any advice on what I'm looking for? The first error I see is on connect:
```
Outbound: Sending CHANNEL_OPEN (r:13, session)
Socket error: read ECONNRESET
```

**Comment by sanketbajoria** [comment]
@flyfishMT 
Can you please explain.. how are you using this library
Do we open single ssh connection. And, then, we use this same ssh connection to exec command. (Is there a lot of gap, in between to exec command.)
Or do we open new connection every time, to exec the command.

**Comment by sanketbajoria** [comment]
@flyfishMT 
Seems to me ssh connection is dropping. Can you set KeepAliveInterval, so that persistent connection can be established. 
```
const ssh = new SSH2Promise({
  host: <hostname>,
  username: <username>,
  identity: <path to private key>,
  keepaliveInterval: 60000,
 keepaliveCountMax: 5
});

```
Or for every request. you can create new ssh connection... exec... and close... But, if the number of request are high... go with above method
In the meanwhile i will try to debug if connection get dropped, then it should get established automatically.

**Comment by flyfishMT** [comment]
Hi @sanketbajoria any luck debugging? I thought I had success with with keepaliveCountMax but it cropped up again. However, I don't remember keepaliveInterval being suggested so I haven't tried that. I also tried to just connect and close every time but am now seeing "Error: No Connection" for a time, and then it will work intermittently.  For option 2 of re-creating the connection every time, do you recommend instantiating at the module level as in my first comment, or perhaps re-instantiate every time in the exported function that does the work?
